name = "ranger"
version = "0.3.0"

description = "create ranges over any type"
licences = ["Apache-2.0"]
links = [{title = "gleam", href = "https://gleam.run"}]
repository = {type = "github", user = "massivefermion", repo = "ranger"}

[dependencies]
gleam_stdlib = "~> 0.30"

[dev-dependencies]
gleeunit = "~> 0.10"
